INSERT INTO regions VALUES (DEFAULT,'AZ--Phoenix');
INSERT INTO regions VALUES (DEFAULT,'CA--Los Angeles');
INSERT INTO regions VALUES (DEFAULT,'CA--Oakland');
INSERT INTO regions VALUES (DEFAULT,'CA--Sacramento');
INSERT INTO regions VALUES (DEFAULT,'CA--San Diego');
INSERT INTO regions VALUES (DEFAULT,'CA--San Francisco');
INSERT INTO regions VALUES (DEFAULT,'CA--San Jose');
INSERT INTO regions VALUES (DEFAULT,'CO--Denver');
INSERT INTO regions VALUES (DEFAULT,'CT--Hartford');
INSERT INTO regions VALUES (DEFAULT,'DC--Washington');
INSERT INTO regions VALUES (DEFAULT,'FL--Jacksonville');
INSERT INTO regions VALUES (DEFAULT,'FL--Miami');
INSERT INTO regions VALUES (DEFAULT,'FL--Orlando');
INSERT INTO regions VALUES (DEFAULT,'FL--Tampa-St. Pete');
INSERT INTO regions VALUES (DEFAULT,'FL--West Palm Beach');
INSERT INTO regions VALUES (DEFAULT,'GA--Atlanta');
INSERT INTO regions VALUES (DEFAULT,'HI--Honolulu');
INSERT INTO regions VALUES (DEFAULT,'ID--Billings-Boise');
INSERT INTO regions VALUES (DEFAULT,'IL--Chicago');
INSERT INTO regions VALUES (DEFAULT,'IN--Indianapolis');
INSERT INTO regions VALUES (DEFAULT,'KS--Kansas City');
INSERT INTO regions VALUES (DEFAULT,'KY--Louisville');
INSERT INTO regions VALUES (DEFAULT,'LA--New Orleans');
INSERT INTO regions VALUES (DEFAULT,'MA--Boston ');
INSERT INTO regions VALUES (DEFAULT,'MD--Baltimore');
INSERT INTO regions VALUES (DEFAULT,'MI--Detroit');
INSERT INTO regions VALUES (DEFAULT,'MI--Grand Rapids');
INSERT INTO regions VALUES (DEFAULT,'MN--Minn-St. Paul');
INSERT INTO regions VALUES (DEFAULT,'MO--Kansas City');
INSERT INTO regions VALUES (DEFAULT,'MO--St. Louis');
INSERT INTO regions VALUES (DEFAULT,'MT--Billings-Boise');
INSERT INTO regions VALUES (DEFAULT,'NC--Charlotte');
INSERT INTO regions VALUES (DEFAULT,'NC--Greensboro');
INSERT INTO regions VALUES (DEFAULT,'NC--Raleigh-Durham');
INSERT INTO regions VALUES (DEFAULT,'ND--Bismarck-Pierre');
INSERT INTO regions VALUES (DEFAULT,'NM--Albuquerque');
INSERT INTO regions VALUES (DEFAULT,'NV--Las Vegas');
INSERT INTO regions VALUES (DEFAULT,'NY--Albany');
INSERT INTO regions VALUES (DEFAULT,'NY--Buffalo');
INSERT INTO regions VALUES (DEFAULT,'NY--New York');
INSERT INTO regions VALUES (DEFAULT,'NY--Rochester');
INSERT INTO regions VALUES (DEFAULT,'OH--Cincinnati');
INSERT INTO regions VALUES (DEFAULT,'OH--Cleveland');
INSERT INTO regions VALUES (DEFAULT,'OH--Columbus');
INSERT INTO regions VALUES (DEFAULT,'OH--Dayton');
INSERT INTO regions VALUES (DEFAULT,'OK--Oklahoma City');
INSERT INTO regions VALUES (DEFAULT,'OR--Portland');
INSERT INTO regions VALUES (DEFAULT,'PA--Philadelphia');
INSERT INTO regions VALUES (DEFAULT,'PA--Pittsburgh');
INSERT INTO regions VALUES (DEFAULT,'RI--Providence');
INSERT INTO regions VALUES (DEFAULT,'SD--Bismarck-Pierre');
INSERT INTO regions VALUES (DEFAULT,'TN--Memphis');
INSERT INTO regions VALUES (DEFAULT,'TN--Nashville');
INSERT INTO regions VALUES (DEFAULT,'TX--Austin');
INSERT INTO regions VALUES (DEFAULT,'TX--Dallas-Fort Worth');
INSERT INTO regions VALUES (DEFAULT,'TX--Houston');
INSERT INTO regions VALUES (DEFAULT,'TX--San Antonio');
INSERT INTO regions VALUES (DEFAULT,'UT--Salt Lake City');
INSERT INTO regions VALUES (DEFAULT,'VA--Norfolk-VA Beach');
INSERT INTO regions VALUES (DEFAULT,'VA--Richmond');
INSERT INTO regions VALUES (DEFAULT,'WA--Seattle-Tacoma');
INSERT INTO regions VALUES (DEFAULT,'WI--Milwaukee');

INSERT INTO categories VALUES (DEFAULT,'Antiques & Art ');
INSERT INTO categories VALUES (DEFAULT,'Books ');
INSERT INTO categories VALUES (DEFAULT,'Business, Office & Industrial ');
INSERT INTO categories VALUES (DEFAULT,'Clothing & Accessories ');
INSERT INTO categories VALUES (DEFAULT,'Coins ');
INSERT INTO categories VALUES (DEFAULT,'Collectibles ');
INSERT INTO categories VALUES (DEFAULT,'Computers ');
INSERT INTO categories VALUES (DEFAULT,'Consumer Electronics ');
INSERT INTO categories VALUES (DEFAULT,'Dolls & Bears ');
INSERT INTO categories VALUES (DEFAULT,'Home & Garden ');
INSERT INTO categories VALUES (DEFAULT,'Jewelry, Gems & Watches ');
INSERT INTO categories VALUES (DEFAULT,'Movies & Television ');
INSERT INTO categories VALUES (DEFAULT,'Music ');
INSERT INTO categories VALUES (DEFAULT,'Photo ');
INSERT INTO categories VALUES (DEFAULT,'Pottery & Glass ');
INSERT INTO categories VALUES (DEFAULT,'Sports ');
INSERT INTO categories VALUES (DEFAULT,'Stamps ');
INSERT INTO categories VALUES (DEFAULT,'Tickets & Travel ');
INSERT INTO categories VALUES (DEFAULT,'Toys & Hobbies ');
INSERT INTO categories VALUES (DEFAULT,'Everything Else ');