/**
 * Autogenerated by Thrift Compiler (0.16.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package pl.poznan.put.kacperwleklak.cab.protocol;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.16.0)", date = "2022-08-19")
public class CabMessage implements org.apache.thrift.TBase<CabMessage, CabMessage._Fields>, java.io.Serializable, Cloneable, Comparable<CabMessage> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("CabMessage");

  private static final org.apache.thrift.protocol.TField MESSAGE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("messageID", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField PREDICATE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("predicateId", org.apache.thrift.protocol.TType.BYTE, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new CabMessageStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new CabMessageTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable CabMessageID messageID; // required
  public byte predicateId; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE_ID((short)1, "messageID"),
    PREDICATE_ID((short)2, "predicateId");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE_ID
          return MESSAGE_ID;
        case 2: // PREDICATE_ID
          return PREDICATE_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __PREDICATEID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.PREDICATE_ID};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE_ID, new org.apache.thrift.meta_data.FieldMetaData("messageID", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CabMessageID.class)));
    tmpMap.put(_Fields.PREDICATE_ID, new org.apache.thrift.meta_data.FieldMetaData("predicateId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BYTE)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(CabMessage.class, metaDataMap);
  }

  public CabMessage() {
  }

  public CabMessage(
    CabMessageID messageID)
  {
    this();
    this.messageID = messageID;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public CabMessage(CabMessage other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessageID()) {
      this.messageID = new CabMessageID(other.messageID);
    }
    this.predicateId = other.predicateId;
  }

  public CabMessage deepCopy() {
    return new CabMessage(this);
  }

  @Override
  public void clear() {
    this.messageID = null;
    setPredicateIdIsSet(false);
    this.predicateId = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public CabMessageID getMessageID() {
    return this.messageID;
  }

  public CabMessage setMessageID(@org.apache.thrift.annotation.Nullable CabMessageID messageID) {
    this.messageID = messageID;
    return this;
  }

  public void unsetMessageID() {
    this.messageID = null;
  }

  /** Returns true if field messageID is set (has been assigned a value) and false otherwise */
  public boolean isSetMessageID() {
    return this.messageID != null;
  }

  public void setMessageIDIsSet(boolean value) {
    if (!value) {
      this.messageID = null;
    }
  }

  public byte getPredicateId() {
    return this.predicateId;
  }

  public CabMessage setPredicateId(byte predicateId) {
    this.predicateId = predicateId;
    setPredicateIdIsSet(true);
    return this;
  }

  public void unsetPredicateId() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PREDICATEID_ISSET_ID);
  }

  /** Returns true if field predicateId is set (has been assigned a value) and false otherwise */
  public boolean isSetPredicateId() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PREDICATEID_ISSET_ID);
  }

  public void setPredicateIdIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PREDICATEID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable Object value) {
    switch (field) {
    case MESSAGE_ID:
      if (value == null) {
        unsetMessageID();
      } else {
        setMessageID((CabMessageID)value);
      }
      break;

    case PREDICATE_ID:
      if (value == null) {
        unsetPredicateId();
      } else {
        setPredicateId((Byte)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE_ID:
      return getMessageID();

    case PREDICATE_ID:
      return getPredicateId();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE_ID:
      return isSetMessageID();
    case PREDICATE_ID:
      return isSetPredicateId();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that instanceof CabMessage)
      return this.equals((CabMessage)that);
    return false;
  }

  public boolean equals(CabMessage that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_messageID = true && this.isSetMessageID();
    boolean that_present_messageID = true && that.isSetMessageID();
    if (this_present_messageID || that_present_messageID) {
      if (!(this_present_messageID && that_present_messageID))
        return false;
      if (!this.messageID.equals(that.messageID))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessageID()) ? 131071 : 524287);
    if (isSetMessageID())
      hashCode = hashCode * 8191 + messageID.hashCode();

    hashCode = hashCode * 8191 + ((isSetPredicateId()) ? 131071 : 524287);
    if (isSetPredicateId())
      hashCode = hashCode * 8191 + (int) (predicateId);

    return hashCode;
  }

  @Override
  public int compareTo(CabMessage other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.compare(isSetMessageID(), other.isSetMessageID());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessageID()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.messageID, other.messageID);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.compare(isSetPredicateId(), other.isSetPredicateId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPredicateId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.predicateId, other.predicateId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("CabMessage(");
    boolean first = true;

    sb.append("messageID:");
    if (this.messageID == null) {
      sb.append("null");
    } else {
      sb.append(this.messageID);
    }
    first = false;
    if (isSetPredicateId()) {
      if (!first) sb.append(", ");
      sb.append("predicateId:");
      sb.append(this.predicateId);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (messageID != null) {
      messageID.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class CabMessageStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CabMessageStandardScheme getScheme() {
      return new CabMessageStandardScheme();
    }
  }

  private static class CabMessageStandardScheme extends org.apache.thrift.scheme.StandardScheme<CabMessage> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, CabMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.messageID = new CabMessageID();
              struct.messageID.read(iprot);
              struct.setMessageIDIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PREDICATE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.BYTE) {
              struct.predicateId = iprot.readByte();
              struct.setPredicateIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, CabMessage struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.messageID != null) {
        oprot.writeFieldBegin(MESSAGE_ID_FIELD_DESC);
        struct.messageID.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.isSetPredicateId()) {
        oprot.writeFieldBegin(PREDICATE_ID_FIELD_DESC);
        oprot.writeByte(struct.predicateId);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class CabMessageTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public CabMessageTupleScheme getScheme() {
      return new CabMessageTupleScheme();
    }
  }

  private static class CabMessageTupleScheme extends org.apache.thrift.scheme.TupleScheme<CabMessage> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, CabMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetMessageID()) {
        optionals.set(0);
      }
      if (struct.isSetPredicateId()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetMessageID()) {
        struct.messageID.write(oprot);
      }
      if (struct.isSetPredicateId()) {
        oprot.writeByte(struct.predicateId);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, CabMessage struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.messageID = new CabMessageID();
        struct.messageID.read(iprot);
        struct.setMessageIDIsSet(true);
      }
      if (incoming.get(1)) {
        struct.predicateId = iprot.readByte();
        struct.setPredicateIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

